name: Execute notebook

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - run: | 
        pip install -r requirements.txt
        pip install nbconvert 
    - name: Run notebook
      run: jupyter-nbconvert lardon.ipynb --to notebook --execute
    

